document:
  name: Guida allo sviluppo e gestione di software libero 
  description: |
    Guida allo sviluppo e gestione di software libero
  tags:
    - developers  
    - software libero 
    - open source
    - FLOSS
    - community
    - Public Administration
